import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AutosProvider } from "../context/AutosContext";
import { UsuariosProvider } from '../context/UsuariosContext';
import PieDePagina from "./pie/PieDePagina";
import Cabecera from "./cabecera/Cabecera";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UsuariosProvider>
          <AutosProvider>
            <Cabecera />
            <main>
              {children}
            </main>
            <PieDePagina />
          </AutosProvider>
        </UsuariosProvider>
      </body>
    </html>
  );
}
